import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Sends the image to Gemini to remove the background and replace it with solid black.
 * @param base64Image The captured image in base64 format (data:image/jpeg;base64,...)
 */
export const processImageBackground = async (base64Image: string): Promise<string> => {
  try {
    // Extract base64 data (remove header if present)
    const base64Data = base64Image.split(',')[1] || base64Image;

    const model = 'gemini-2.5-flash-image';
    
    // Prompt designed for strict background replacement
    const prompt = "Strictly keep the main person/subject in the foreground exactly as they are. Do not change their face, expression, or lighting. Replace the entire background with pure solid black color hex code #000000. Ensure clean edges around the subject.";

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            text: prompt,
          },
          {
            inlineData: {
              data: base64Data,
              mimeType: 'image/jpeg',
            },
          },
        ],
      },
    });

    // Check for image parts in the response
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
           return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini processing error:", error);
    throw error;
  }
};